#!/bin/bash

for src_test_name_ext in src/test_*
do
  test_name_ext=$(basename $src_test_name_ext)
  test_name="${test_name_ext%.*}"
  test_bin="bin/$(uname -s)-$(uname -m)/$test_name"
  if ! make "$test_bin"
  then
    fail="$fail make!$test_name"
  else
    if [ -x "$test_bin" ] && ./$test_bin
    then
      pass="$pass $test_name"
    else
      fail="$fail $test_name"
    fi
  fi
done

if [ "$pass" != "" ]
then
  echo "passed build&test:$pass"
fi
if [ "$fail" != "" ]
then
   echo "failed build|test:$fail"
   exit 1
fi

echo "all built/test passed!"
exit 0

